"""make hash unique in File

Revision ID: 8c63e73510ea
Revises: 996960375c9c
Create Date: 2025-07-25 11:10:54.592810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '8c63e73510ea'
down_revision: Union[str, Sequence[str], None] = '996960375c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'File', ['hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'File', type_='unique')
    # ### end Alembic commands ###
