"""add hash to File

Revision ID: 996960375c9c
Revises: 4ce14e902894
Create Date: 2025-07-25 10:55:50.343539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '996960375c9c'
down_revision: Union[str, Sequence[str], None] = '4ce14e902894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('File', sa.Column('hash', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('File', 'hash')
    # ### end Alembic commands ###
