"""add file upload status fields

Revision ID: bd6f5bdbeb7c
Revises: ffded7d5b949
Create Date: 2025-07-18 11:11:06.785618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'bd6f5bdbeb7c'
down_revision: Union[str, Sequence[str], None] = 'ffded7d5b949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type first
    filestatus_enum = sa.Enum('UPLOADING', 'PROCESSING', 'COMPLETED', 'FAILED', name='filestatus')
    filestatus_enum.create(op.get_bind(), checkfirst=True)
    
    # Add columns with proper defaults
    op.add_column('File', sa.Column('status', filestatus_enum, nullable=False, server_default='UPLOADING'))
    op.add_column('File', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True, server_default=''))
    op.add_column('File', sa.Column('file_size', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('File', sa.Column('upload_progress', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('File', 'upload_progress')
    op.drop_column('File', 'file_size')
    op.drop_column('File', 'error_message')
    op.drop_column('File', 'status')
    
    # Drop the ENUM type
    sa.Enum(name='filestatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
