"""add model field

Revision ID: e64d21e29941
Revises: 8c63e73510ea
Create Date: 2025-07-29 13:10:30.213280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'e64d21e29941'
down_revision: Union[str, Sequence[str], None] = '8c63e73510ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chat_history', sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Chat_history', 'model')
    # ### end Alembic commands ###
