"""File allows the same name, but path is unique

Revision ID: f46e0e1e68c9
Revises: e04634f4efea
Create Date: 2025-08-13 09:02:42.449196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f46e0e1e68c9'
down_revision: Union[str, Sequence[str], None] = 'e04634f4efea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('File_name_key'), 'File', type_='unique')
    op.create_unique_constraint(None, 'File', ['link'])
    op.alter_column('token_blacklist', 'blacklisted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('token_blacklist', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token_blacklist', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('token_blacklist', 'blacklisted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'File', type_='unique')
    op.create_unique_constraint(op.f('File_name_key'), 'File', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
