"""add 'type' attribute to File

Revision ID: ffded7d5b949
Revises: 6abfac839ce7
Create Date: 2025-07-16 11:48:39.900832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ffded7d5b949'
down_revision: Union[str, Sequence[str], None] = '6abfac839ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('File', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('File', 'type')
    # ### end Alembic commands ###
